#############################################################################
# Makefile for building: ctx2000
# Generated by qmake (2.01a) (Qt 4.7.0) on: ?? 4? 6 17:24:20 2011
# Project:  ctx2000.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/byteman/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger -o Makefile ctx2000.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -D_PC_DBG
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4 -I/usr/local/include/yate -Iguicore/include -Iime -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lPocoFoundation -L./extlib/x86 -L./guicore/lib/libpc -lyate -lminigui -lmgext -lpng -ljpeg -lguicore -lsqlite3 -lserial -lttf -lPocoNet -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ../tmpobj/x86/

####### Files

SOURCES       = Main.cpp \
		LoginForm.cpp \
		MainMenu.cpp \
		ime/SoftKeyboardForm.cpp \
		ime/SoftKeyboard.cpp \
		ime/mgphone.c \
		ime/mgime.c \
		ime/keyboard.c \
		ime/jt_engine.c \
		ime/hwinput.c \
		ime/hw_engine.c \
		ime/ime_pinyin.c \
		ime/mgpti.c \
		ime/mgpti_dict.c \
		ime/mgpti_user_dict.c \
		ime/mgpti_dict_ops.c \
		ime/mgpti_helper.c \
		ime/mgiSet.cpp \
		statusicon.cpp \
		dirstatus.cpp \
		taji.cpp \
		CppSQLite3.cpp \
		tajidbmgr.cpp \
		SysSet.cpp \
		worksite.cpp \
		iniFile.cpp \
		dataacquire.cpp \
		diantai.cpp \
		mainctrl.cpp \
		formworksite.cpp \
		centerrecver.cpp \
		formcalib.cpp \
		formcalibdist.cpp \
		AlarmInfoManForm.cpp \
		comdata.cpp \
		tcparam.cpp \
		divparam.cpp \
		lijuConfForm.cpp \
		MineAddBox.cpp \
		lijuctrl.cpp \
		biaoding.cpp 
OBJECTS       = ../tmpobj/x86/Main.o \
		../tmpobj/x86/LoginForm.o \
		../tmpobj/x86/MainMenu.o \
		../tmpobj/x86/SoftKeyboardForm.o \
		../tmpobj/x86/SoftKeyboard.o \
		../tmpobj/x86/mgphone.o \
		../tmpobj/x86/mgime.o \
		../tmpobj/x86/keyboard.o \
		../tmpobj/x86/jt_engine.o \
		../tmpobj/x86/hwinput.o \
		../tmpobj/x86/hw_engine.o \
		../tmpobj/x86/ime_pinyin.o \
		../tmpobj/x86/mgpti.o \
		../tmpobj/x86/mgpti_dict.o \
		../tmpobj/x86/mgpti_user_dict.o \
		../tmpobj/x86/mgpti_dict_ops.o \
		../tmpobj/x86/mgpti_helper.o \
		../tmpobj/x86/mgiSet.o \
		../tmpobj/x86/statusicon.o \
		../tmpobj/x86/dirstatus.o \
		../tmpobj/x86/taji.o \
		../tmpobj/x86/CppSQLite3.o \
		../tmpobj/x86/tajidbmgr.o \
		../tmpobj/x86/SysSet.o \
		../tmpobj/x86/worksite.o \
		../tmpobj/x86/iniFile.o \
		../tmpobj/x86/dataacquire.o \
		../tmpobj/x86/diantai.o \
		../tmpobj/x86/mainctrl.o \
		../tmpobj/x86/formworksite.o \
		../tmpobj/x86/centerrecver.o \
		../tmpobj/x86/formcalib.o \
		../tmpobj/x86/formcalibdist.o \
		../tmpobj/x86/AlarmInfoManForm.o \
		../tmpobj/x86/comdata.o \
		../tmpobj/x86/tcparam.o \
		../tmpobj/x86/divparam.o \
		../tmpobj/x86/lijuConfForm.o \
		../tmpobj/x86/MineAddBox.o \
		../tmpobj/x86/lijuctrl.o \
		../tmpobj/x86/biaoding.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ctx2000.pro
QMAKE_TARGET  = ctx2000
DESTDIR       = 
TARGET        = ctx2000

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ctx2000.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/byteman/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger -o Makefile ctx2000.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/home/byteman/qtcreator-2.0.94/share/qtcreator/qml/qmljsdebugger -o Makefile ctx2000.pro

dist: 
	@$(CHK_DIR_EXISTS) ../tmpobj/x86/ctx20001.0.0 || $(MKDIR) ../tmpobj/x86/ctx20001.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../tmpobj/x86/ctx20001.0.0/ && $(COPY_FILE) --parents ime/wt_input.h ime/SoftKeyboardForm.h ime/SoftKeyboard.h ime/mgphone.h ime/mgime_tab.h ime/mgime.h ime/keyboard.h ime/jt_input.h ime/ime_pinyin.h ime/hwinput.h ime/hw_engine.h ime/hw.h ime/config.h statusicon.h dirstatus.h ctx2000.h taji.h collalgo.h CppSQLite3.h tajidbmgr.h SysSetItem.h SysSet.h worksiteitem.h worksite.h dataacquire.h diantai.h mainctrl.h formworksite.h centerrecver.h formcalib.h formcalibitem.h formcalibdistitem.h formcalibdist.h AlarmInfoManForm.h AlarmInfoManFormItem.h comdata.h tcparam.h divparam.h divparamitem.h lijuConfForm.h lijuConfFormItem.h ModeAddBox.h ModeAddBoxItem.h MineAddBox.h MineAddBoxItem.h lijuctrl.h biaoding.h ../tmpobj/x86/ctx20001.0.0/ && $(COPY_FILE) --parents Main.cpp LoginForm.cpp MainMenu.cpp ime/SoftKeyboardForm.cpp ime/SoftKeyboard.cpp ime/mgphone.c ime/mgime.c ime/keyboard.c ime/jt_engine.c ime/hwinput.c ime/hw_engine.c ime/ime_pinyin.c ime/mgpti.c ime/mgpti_dict.c ime/mgpti_user_dict.c ime/mgpti_dict_ops.c ime/mgpti_helper.c ime/mgiSet.cpp statusicon.cpp dirstatus.cpp taji.cpp CppSQLite3.cpp tajidbmgr.cpp SysSet.cpp worksite.cpp iniFile.cpp dataacquire.cpp diantai.cpp mainctrl.cpp formworksite.cpp centerrecver.cpp formcalib.cpp formcalibdist.cpp AlarmInfoManForm.cpp comdata.cpp tcparam.cpp divparam.cpp lijuConfForm.cpp MineAddBox.cpp lijuctrl.cpp biaoding.cpp ../tmpobj/x86/ctx20001.0.0/ && (cd `dirname ../tmpobj/x86/ctx20001.0.0` && $(TAR) ctx20001.0.0.tar ctx20001.0.0 && $(COMPRESS) ctx20001.0.0.tar) && $(MOVE) `dirname ../tmpobj/x86/ctx20001.0.0`/ctx20001.0.0.tar.gz . && $(DEL_FILE) -r ../tmpobj/x86/ctx20001.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

../tmpobj/x86/Main.o: Main.cpp LoginForm.h \
		dataacquire.h \
		ctx2000.h \
		collalgo.h \
		mainctrl.h \
		tajidbmgr.h \
		CppSQLite3.h \
		diantai.h \
		MainMenu.h \
		dirstatus.h \
		taji.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/Main.o Main.cpp

../tmpobj/x86/LoginForm.o: LoginForm.cpp LoginFormItem.h \
		LoginForm.h \
		dataacquire.h \
		ctx2000.h \
		collalgo.h \
		BmpRes.h \
		MainMenu.h \
		dirstatus.h \
		taji.h \
		tajidbmgr.h \
		CppSQLite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/LoginForm.o LoginForm.cpp

../tmpobj/x86/MainMenu.o: MainMenu.cpp MainMenuItem.h \
		MainMenu.h \
		dirstatus.h \
		ctx2000.h \
		collalgo.h \
		taji.h \
		statusicon.h \
		BmpRes.h \
		SysSet.h \
		tajidbmgr.h \
		CppSQLite3.h \
		formworksite.h \
		lijuConfForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/MainMenu.o MainMenu.cpp

../tmpobj/x86/SoftKeyboardForm.o: ime/SoftKeyboardForm.cpp ime/SoftKeyboardForm.h \
		ime/SoftKeyboard.h \
		ime/mgiSet.h \
		ime/mgime.h \
		ime/keyboard.h \
		ime/mgphone.h \
		ime/hwinput.h \
		ime/hw_engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/SoftKeyboardForm.o ime/SoftKeyboardForm.cpp

../tmpobj/x86/SoftKeyboard.o: ime/SoftKeyboard.cpp ime/SoftKeyboard.h \
		ime/mgiSet.h \
		ime/mgime.h \
		ime/keyboard.h \
		ime/mgphone.h \
		ime/hwinput.h \
		ime/hw_engine.h \
		ime/SoftKeyboardForm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/SoftKeyboard.o ime/SoftKeyboard.cpp

../tmpobj/x86/mgphone.o: ime/mgphone.c ime/mgphone.h \
		ime/mgphone_nav_bmp.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgphone.o ime/mgphone.c

../tmpobj/x86/mgime.o: ime/mgime.c ime/mgime.h \
		ime/contbmp.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgime.o ime/mgime.c

../tmpobj/x86/keyboard.o: ime/keyboard.c ime/config.h \
		ime/keyboard.h \
		ime/mgime.h \
		ime/default_kb_bmp.c \
		ime/mgime_tab.h \
		ime/skb_bmp.c
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/keyboard.o ime/keyboard.c

../tmpobj/x86/jt_engine.o: ime/jt_engine.c ime/jt_input.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/jt_engine.o ime/jt_engine.c

../tmpobj/x86/hwinput.o: ime/hwinput.c ime/hw.h \
		ime/hwinput.h \
		ime/hw_engine.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/hwinput.o ime/hwinput.c

../tmpobj/x86/hw_engine.o: ime/hw_engine.c ime/hw_engine.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/hw_engine.o ime/hw_engine.c

../tmpobj/x86/ime_pinyin.o: ime/ime_pinyin.c ime/ime_pinyin.h \
		ime/ime_tab_pinyin.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/ime_pinyin.o ime/ime_pinyin.c

../tmpobj/x86/mgpti.o: ime/mgpti.c ime/mgpti.h \
		ime/mgphone.h \
		ime/mgpti_dict.h \
		ime/mgpti_dict_ops.h \
		ime/mgpti_user_dict.h \
		ime/mgpti_helper.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgpti.o ime/mgpti.c

../tmpobj/x86/mgpti_dict.o: ime/mgpti_dict.c ime/mgpti_dict.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgpti_dict.o ime/mgpti_dict.c

../tmpobj/x86/mgpti_user_dict.o: ime/mgpti_user_dict.c ime/mgpti.h \
		ime/mgphone.h \
		ime/mgpti_dict.h \
		ime/mgpti_dict_ops.h \
		ime/mgpti_user_dict.h \
		ime/mgpti_helper.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgpti_user_dict.o ime/mgpti_user_dict.c

../tmpobj/x86/mgpti_dict_ops.o: ime/mgpti_dict_ops.c ime/mgpti.h \
		ime/mgphone.h \
		ime/mgpti_dict.h \
		ime/mgpti_dict_ops.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgpti_dict_ops.o ime/mgpti_dict_ops.c

../tmpobj/x86/mgpti_helper.o: ime/mgpti_helper.c ime/mgpti.h \
		ime/mgphone.h \
		ime/mgpti_helper.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o ../tmpobj/x86/mgpti_helper.o ime/mgpti_helper.c

../tmpobj/x86/mgiSet.o: ime/mgiSet.cpp ime/mgiSet.h \
		ime/mgime.h \
		ime/keyboard.h \
		ime/mgphone.h \
		ime/hwinput.h \
		ime/hw_engine.h \
		ime/ime_pinyin.h \
		ime/mgpti.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/mgiSet.o ime/mgiSet.cpp

../tmpobj/x86/statusicon.o: statusicon.cpp statusicon.h \
		ctx2000.h \
		collalgo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/statusicon.o statusicon.cpp

../tmpobj/x86/dirstatus.o: dirstatus.cpp dirstatus.h \
		ctx2000.h \
		collalgo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/dirstatus.o dirstatus.cpp

../tmpobj/x86/taji.o: taji.cpp taji.h \
		collalgo.h \
		CppSQLite3.h \
		tajidbmgr.h \
		ctx2000.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/taji.o taji.cpp

../tmpobj/x86/CppSQLite3.o: CppSQLite3.cpp CppSQLite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/CppSQLite3.o CppSQLite3.cpp

../tmpobj/x86/tajidbmgr.o: tajidbmgr.cpp tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		iniFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/tajidbmgr.o tajidbmgr.cpp

../tmpobj/x86/SysSet.o: SysSet.cpp SysSetItem.h \
		SysSet.h \
		taji.h \
		collalgo.h \
		worksite.h \
		formcalib.h \
		formcalibdist.h \
		AlarmInfoManForm.h \
		tajidbmgr.h \
		ctx2000.h \
		CppSQLite3.h \
		tcparam.h \
		divparam.h \
		BmpRes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/SysSet.o SysSet.cpp

../tmpobj/x86/worksite.o: worksite.cpp worksite.h \
		worksiteitem.h \
		BmpRes.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		iniFile.h \
		comdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/worksite.o worksite.cpp

../tmpobj/x86/iniFile.o: iniFile.cpp iniFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/iniFile.o iniFile.cpp

../tmpobj/x86/dataacquire.o: dataacquire.cpp dataacquire.h \
		ctx2000.h \
		collalgo.h \
		tajidbmgr.h \
		CppSQLite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/dataacquire.o dataacquire.cpp

../tmpobj/x86/diantai.o: diantai.cpp diantai.h \
		ctx2000.h \
		collalgo.h \
		tajidbmgr.h \
		CppSQLite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/diantai.o diantai.cpp

../tmpobj/x86/mainctrl.o: mainctrl.cpp mainctrl.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		dataacquire.h \
		diantai.h \
		centerrecver.h \
		iniFile.h \
		comdata.h \
		lijuctrl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/mainctrl.o mainctrl.cpp

../tmpobj/x86/formworksite.o: formworksite.cpp formworksite.h \
		taji.h \
		collalgo.h \
		tajidbmgr.h \
		ctx2000.h \
		CppSQLite3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/formworksite.o formworksite.cpp

../tmpobj/x86/centerrecver.o: centerrecver.cpp centerrecver.h \
		ctx2000.h \
		collalgo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/centerrecver.o centerrecver.cpp

../tmpobj/x86/formcalib.o: formcalib.cpp formcalib.h \
		formcalibitem.h \
		BmpRes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/formcalib.o formcalib.cpp

../tmpobj/x86/formcalibdist.o: formcalibdist.cpp formcalibdist.h \
		formcalibdistitem.h \
		BmpRes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/formcalibdist.o formcalibdist.cpp

../tmpobj/x86/AlarmInfoManForm.o: AlarmInfoManForm.cpp AlarmInfoManFormItem.h \
		AlarmInfoManForm.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		BmpRes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/AlarmInfoManForm.o AlarmInfoManForm.cpp

../tmpobj/x86/comdata.o: comdata.cpp comdata.h \
		ctx2000.h \
		collalgo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/comdata.o comdata.cpp

../tmpobj/x86/tcparam.o: tcparam.cpp tcparam.h \
		tcparamitem.h \
		BmpRes.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		iniFile.h \
		comdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/tcparam.o tcparam.cpp

../tmpobj/x86/divparam.o: divparam.cpp divparam.h \
		divparamitem.h \
		BmpRes.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		iniFile.h \
		comdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/divparam.o divparam.cpp

../tmpobj/x86/lijuConfForm.o: lijuConfForm.cpp lijuConfFormItem.h \
		lijuConfForm.h \
		BmpRes.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		MineAddBox.h \
		comdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/lijuConfForm.o lijuConfForm.cpp

../tmpobj/x86/MineAddBox.o: MineAddBox.cpp MineAddBox.h \
		MineAddBoxItem.h \
		BmpRes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/MineAddBox.o MineAddBox.cpp

../tmpobj/x86/lijuctrl.o: lijuctrl.cpp lijuctrl.h \
		tajidbmgr.h \
		ctx2000.h \
		collalgo.h \
		CppSQLite3.h \
		comdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/lijuctrl.o lijuctrl.cpp

../tmpobj/x86/biaoding.o: biaoding.cpp biaoding.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../tmpobj/x86/biaoding.o biaoding.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

