#define COMMON_CTRL_STYLE_NUM		4 //2

#define CENTER_EDIT_PORT_CLASS		CTRL_EDIT
#define CENTER_EDIT_PORT_STYLE		WS_VISIBLE|WS_GROUP|ES_DIGIT_ONLY
#define CENTER_EDIT_PORT_X			610
#define CENTER_EDIT_PORT_Y			125 //75
#define CENTER_EDIT_PORT_W			160
#define CENTER_EDIT_PORT_H					36
#define CENTER_EDIT_PORT_ID				100
#define CENTER_EDIT_PORT_CAPTION		""
#define CENTER_EDIT_PORT_ADDDATA		0
#define CENTER_EDIT_PORT_EXSTYLE		WS_EX_TRANSPARENT

#define MEDIA_EDIT_PORT_CLASS		CTRL_EDIT
#define MEDIA_EDIT_PORT_STYLE		WS_VISIBLE|WS_GROUP|ES_DIGIT_ONLY
#define MEDIA_EDIT_PORT_X			610
#define MEDIA_EDIT_PORT_Y			175 //125
#define MEDIA_EDIT_PORT_W			160
#define MEDIA_EDIT_PORT_H					36
#define MEDIA_EDIT_PORT_ID				101
#define MEDIA_EDIT_PORT_CAPTION		""
#define MEDIA_EDIT_PORT_ADDDATA		0
#define MEDIA_EDIT_PORT_EXSTYLE		WS_EX_TRANSPARENT

#define DEV_ID_EDIT_CLASS		CTRL_EDIT
#define DEV_ID_EDIT_STYLE		WS_VISIBLE|WS_GROUP
#define DEV_ID_EDIT_X			360
#define DEV_ID_EDIT_Y			75
#define DEV_ID_EDIT_W			160
#define DEV_ID_EDIT_H					36
#define DEV_ID_EDIT_ID				102
#define DEV_ID_EDIT_CAPTION		""
#define DEV_ID_EDIT_ADDDATA		0
#define DEV_ID_EDIT_EXSTYLE		WS_EX_TRANSPARENT

#define DEV_NAME_EDIT_CLASS		CTRL_EDIT
#define DEV_NAME_EDIT_STYLE		WS_VISIBLE|WS_GROUP
#define DEV_NAME_EDIT_X			610
#define DEV_NAME_EDIT_Y			75
#define DEV_NAME_EDIT_W			160
#define DEV_NAME_EDIT_H					36
#define DEV_NAME_EDIT_ID				103
#define DEV_NAME_EDIT_CAPTION		""
#define DEV_NAME_EDIT_ADDDATA		0
#define DEV_NAME_EDIT_EXSTYLE		WS_EX_TRANSPARENT

#define SKIN_CTRL_STYLE_NUM		4//5

#define	BUTTON_OK_ID					1
#define	BUTTON_OK_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_OK_X						370
#define	BUTTON_OK_Y						410
#define	BUTTON_OK_ITEMRC			{}
#define	BUTTON_OK_BMPINDEX		1
#define	BUTTON_OK_TIP					NULL
#define	BUTTON_OK_ATTACHED		0
#define	BUTTON_OK_DATA				NULL

#define	BUTTON_CANCEL_ID					2
#define	BUTTON_CANCEL_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_CANCEL_X						630
#define	BUTTON_CANCEL_Y						410
#define	BUTTON_CANCEL_ITEMRC			{}
#define	BUTTON_CANCEL_BMPINDEX		2
#define	BUTTON_CANCEL_TIP					NULL
#define	BUTTON_CANCEL_ATTACHED		0
#define	BUTTON_CANCEL_DATA				NULL

#define	BUTTON_EXIT_ID					3
#define	BUTTON_EXIT_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_EXIT_X						738
#define	BUTTON_EXIT_Y						8
#define	BUTTON_EXIT_ITEMRC			{}
#define	BUTTON_EXIT_BMPINDEX		3
#define	BUTTON_EXIT_TIP					NULL
#define	BUTTON_EXIT_ATTACHED		0
#define	BUTTON_EXIT_DATA				NULL

#define	CHECK_ETH0_ID					4
#define	CHECK_ETH0_STYLE				SI_TYPE_CHKBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE|SI_BTNSTATUS_CHECKED
#define	CHECK_ETH0_X				350
#define	CHECK_ETH0_Y				220 //170
#define	CHECK_ETH0_ITEMRC			{}
#define	CHECK_ETH0_BMPINDEX		4
#define	CHECK_ETH0_TIP					NULL
#define	CHECK_ETH0_ATTACHED		0
#define	CHECK_ETH0_DATA				NULL
/*
#define	CHECK_PPP0_ID					5
#define	CHECK_PPP0_STYLE				SI_TYPE_CHKBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	CHECK_PPP0_X				600
#define	CHECK_PPP0_Y				220 //170
#define	CHECK_PPP0_ITEMRC			{}
#define	CHECK_PPP0_BMPINDEX		5
#define	CHECK_PPP0_TIP					NULL
#define	CHECK_PPP0_ATTACHED		0
#define	CHECK_PPP0_DATA				NULL
*/
#define SKIN_BMP_NUM					19 //20 del gprs

#define SYSCFG_X						60
#define SYSCFG_Y						65

#define SYSCFG_TEXT_X						60
#define SYSCFG_TEXT_Y						185

#define LINE_X					62
#define LINE_Y					220

#define SYSCFG_IPSET_X			85
#define SYSCFG_IPSET_Y			225

#define SKIN_MSG_NUM					1

#define BLANK_X					340
#define BLANK_Y					15

/* new style */

#define SKIN_BUTTON_OK        {1,BUTTON_OK_X,       BUTTON_OK_Y}
#define SKIN_BUTTON_CANCEL    {2,BUTTON_CANCEL_X,   BUTTON_CANCEL_Y}
#define SKIN_BUTTON_EXIT      {3,BUTTON_EXIT_X,     BUTTON_EXIT_Y}

#define IPCTRL_LEN            170

#define CENTER_IP_X			220
#define CENTER_IP_Y			118 //70

#define CENTER_PORT_X			220
#define CENTER_PORT_Y			118+60 //70

#define DEV_ID_X			220
#define DEV_ID_Y			118+120

#define CENTER_IPEDIT       {380,118,IPCTRL_LEN,30,"0.0.0.0"} //{350,68,160,30,"0.0.0.0"}
#define CENTER_EDIT_PORT    {380,118+60,CENTER_EDIT_PORT_W,CENTER_EDIT_PORT_H,"56000"}
#define DEV_ID_EDIT         {380,118+120,250,DEV_ID_EDIT_H,"dtu001000000000"}
