// #define COMMON_CTRL_STYLE   SI_TYPE_CONTROL|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
// #define SKIN_BUTTON_STYLE   SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE

#ifndef SYSLOGFORMITEM_H
#define SYSLOGFORMITEM_H

#define COMMON_CTRL_STYLE_NUM		1

#define LIST_ALARMINFO_CLASS			CTRL_LISTVIEW
#define LIST_ALARMINFO_STYLE			WS_CHILD|WS_VISIBLE|WS_VSCROLL|WS_HSCROLL
#define LIST_ALARMINFO_X					50
#define LIST_ALARMINFO_Y					70
#define LIST_ALARMINFO_W					700
#define LIST_ALARMINFO_H					320
#define LIST_ALARMINFO_ID				100
#define LIST_ALARMINFO_CAPTION		"sysloglist"
#define LIST_ALARMINFO_ADDDATA		0
#define LIST_ALARMINFO_EXSTYLE		WS_EX_TRANSPARENT

#define SKIN_CTRL_STYLE_NUM		4

#define	BUTTON_PRE_ID					1
#define	BUTTON_PRE_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_PRE_X						270
#define	BUTTON_PRE_Y						410
#define	BUTTON_PRE_ITEMRC			{}
#define	BUTTON_PRE_BMPINDEX		1
#define	BUTTON_PRE_TIP					NULL
#define	BUTTON_PRE_ATTACHED		0
#define	BUTTON_PRE_DATA				NULL

#define	BUTTON_NEXT_ID					2
#define	BUTTON_NEXT_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_NEXT_X						450
#define	BUTTON_NEXT_Y						410
#define	BUTTON_NEXT_ITEMRC			{}
#define	BUTTON_NEXT_BMPINDEX		2
#define	BUTTON_NEXT_TIP					NULL
#define	BUTTON_NEXT_ATTACHED		0
#define	BUTTON_NEXT_DATA				NULL

#define	BUTTON_QUIT_ID					3
#define	BUTTON_QUIT_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_QUIT_X						630
#define	BUTTON_QUIT_Y						410
#define	BUTTON_QUIT_ITEMRC			{}
#define	BUTTON_QUIT_BMPINDEX		3
#define	BUTTON_QUIT_TIP					NULL
#define	BUTTON_QUIT_ATTACHED		0
#define	BUTTON_QUIT_DATA				NULL

#define	BUTTON_EXIT_ID					4
#define	BUTTON_EXIT_STYLE				SI_TYPE_CMDBUTTON|SI_TEST_SHAPE_RECT|SI_STATUS_VISIBLE
#define	BUTTON_EXIT_X						738
#define	BUTTON_EXIT_Y						8
#define	BUTTON_EXIT_ITEMRC			{}
#define	BUTTON_EXIT_BMPINDEX		4
#define	BUTTON_EXIT_TIP					NULL
#define	BUTTON_EXIT_ATTACHED		0
#define	BUTTON_EXIT_DATA				NULL

#define SKIN_BMP_NUM					4

#define QUERY_X						60
#define QUERY_Y						65

#define QUERY_TEXT_X						60
#define QUERY_TEXT_Y						185

#define LINE_X					62
#define LINE_Y					220

#define QUERY_ALARMINFO_X						85
#define QUERY_ALARMINFO_Y						225

/* new style */
#define LISTVIEW_ALARMINFO       {LIST_ALARMINFO_X, LIST_ALARMINFO_Y, LIST_ALARMINFO_W, LIST_ALARMINFO_H,"0"}
#define SKIN_BUTTON_PRE        {1,BUTTON_PRE_X,BUTTON_PRE_Y}
#define SKIN_BUTTON_NEXT        {2,BUTTON_NEXT_X,BUTTON_NEXT_Y}
#define SKIN_BUTTON_QUIT       {3,BUTTON_QUIT_X,BUTTON_QUIT_Y}
#define SKIN_BUTTON_EXIT       {4,BUTTON_EXIT_X,BUTTON_EXIT_Y}
#define SKIN_BUTTON_ALARM       {5,30, BUTTON_NEXT_Y}
#define SKIN_BUTTON_WEIGHT      {6,130,BUTTON_NEXT_Y}

#endif
