
#define SKIN_CTRL_STYLE_NUM		6

#define	BUTTON_SCALE_X		105
#define	BUTTON_SCALE_Y		385

#define	BUTTON_QUERY_X		210
#define	BUTTON_QUERY_Y		350
#define	BUTTON_PRESET_X		315
#define	BUTTON_PRESET_Y		350
#define	BUTTON_SYSCFG_X		420
#define	BUTTON_SYSCFG_Y		350
#define	BUTTON_CWET_X		525
#define	BUTTON_CWET_Y		350
#define	BUTTON_HELP_X		630
#define	BUTTON_HELP_Y		350

#define SKIN_BUTTON_SCALE       {1,BUTTON_SCALE_X,BUTTON_SCALE_Y}
#define SKIN_BUTTON_QUERY       {2,BUTTON_QUERY_X,BUTTON_QUERY_Y}
#define SKIN_BUTTON_PRESET      {3,60,440}
#define SKIN_BUTTON_SYSCFG      {4,BUTTON_SCALE_X,BUTTON_SCALE_Y}
#define SKIN_BUTTON_WETCFG      {5,30,385}
#define SKIN_BUTTON_HELP        {6,60,360}
